//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cigar
        ///	rebut
        ///	sissy
        ///	humph
        ///	awake
        ///	blush
        ///	focal
        ///	evade
        ///	naval
        ///	serve
        ///	heath
        ///	dwarf
        ///	model
        ///	karma
        ///	stink
        ///	grade
        ///	quiet
        ///	bench
        ///	abate
        ///	feign
        ///	major
        ///	death
        ///	fresh
        ///	crust
        ///	stool
        ///	colon
        ///	abase
        ///	marry
        ///	react
        ///	batty
        ///	pride
        ///	floss
        ///	helix
        ///	croak
        ///	staff
        ///	paper
        ///	unfed
        ///	whelp
        ///	trawl
        ///	outdo
        ///	adobe
        ///	crazy
        ///	sower
        ///	repay
        ///	digit
        ///	crate
        ///	cluck
        ///	spike
        ///	mimic
        ///	pound
        ///	maxim
        ///	linen
        ///	unmet
        ///	flesh
        ///	booby
        ///	forth
        ///	first
        ///	stand
        ///	belly
        ///	ivory
        ///	seedy
        ///	print
        ///	yearn
        ///	drain
        ///	 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Other_potential_List {
            get {
                return ResourceManager.GetString("Other_potential_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aback
        ///abase
        ///abate
        ///abbey
        ///abbot
        ///abhor
        ///abide
        ///abled
        ///abode
        ///abort
        ///about
        ///above
        ///abuse
        ///abyss
        ///acorn
        ///acrid
        ///actor
        ///acute
        ///adage
        ///adapt
        ///adept
        ///admin
        ///admit
        ///adobe
        ///adopt
        ///adore
        ///adorn
        ///adult
        ///affix
        ///afire
        ///afoot
        ///afoul
        ///after
        ///again
        ///agape
        ///agate
        ///agent
        ///agile
        ///aging
        ///aglow
        ///agony
        ///agora
        ///agree
        ///ahead
        ///aider
        ///aisle
        ///alarm
        ///album
        ///alert
        ///algae
        ///alibi
        ///alien
        ///align
        ///alike
        ///alive
        ///allay
        ///alley
        ///allot
        ///allow
        ///alloy
        ///aloft
        ///alone
        ///along
        ///aloof
        ///aloud
        ///alpha
        ///altar
        ///alter
        ///amass
        ///amaze
        ///amber
        ///amble
        ///amend
        ///a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WordList2 {
            get {
                return ResourceManager.GetString("WordList2", resourceCulture);
            }
        }
    }
}
